### ISSUE TITLE
Can't Save/Load config, nil value in variables

### ISSUE THREAD

**Issue by Feynt** [demonnic/EMCO#11]
When attempting to 'emco save' I get the following issue in the debug console:

`LUA ERROR: when running script emco (Alias92),
reason: [string "Script: Code"]:84: attempt to index upvalue 'chatEMCO' (a nil value)`

Similarly if I 'emco load' it will complain:
`LUA ERROR: when running script emco (Alias92),
reason: [string "Script: Code"]:96: attempt to index upvalue 'chatEMCO' (a nil value)`

If I change the script so line 84 reads
`demonnic.chat:save()`

The save issue seems to go away.  Likewise replacing chatEMCO with demonnic.chat on line 96 allows data to load without issues.

**Comment by demonnic** [comment]
Ahh, I think this may have been caused by viewing the script and then not having the resetToDefaults() function called, which is causing the local I setup for it to become nil. I'll get a fix in for this shortly.

**Comment by demonnic** [comment]
Alright, should be able to do `emco update` and pick up the fixed version.

**Comment by Feynt** [comment]
I can confirm save/load works without errors now, but it creates three free floating tabs now, "City", "OOC", and "Group" when loading/starting the client fresh.  They seem to be placed behind the window in Z index, it can be dragged over them, but they are definitely separate of the window and can still be clicked (to no effect).

**Comment by demonnic** [comment]
hmm, I can try to reproduce this but I didn't see it in my testing and I'm not sure off hand why that would be

**Comment by demonnic** [comment]
I am unable to reproduce this locally, can you give me the code you're using to create your EMCO?

**Comment by Feynt** [comment]
It's literally just a fresh download and run after `emco update`.  No fancy self scripting to generate a console.
[EMCO Code 2022-10-04.txt](https://github.com/demonnic/EMCO/files/9704109/EMCO.Code.2022-10-04.txt)

It may be loading additional stuff from the config directory?  I'll have to confirm that tomorrow.

**Comment by demonnic** [comment]
Right, I thought I was in the MDK repo for a moment. What tabs should your EMCO have in it, at the end of the day?

**Comment by Feynt** [comment]
I've attached a screenshot of the tabs I'm using, as well as the free floating tabs slightly above the window
![Screenshot 2022-10-04 140648](https://user-images.githubusercontent.com/1266006/193893512-e477cfa3-be14-4107-98f9-91d34c3237eb.png)

**Comment by demonnic** [comment]
Alright, finally got this to replicate, will try to get it fixed tonight.

**Comment by demonnic** [comment]
ok, I have fixed this. Will get a release pushed in a bit

**Comment by demonnic** [comment]
ok, should be able to update and have the ghosts of tabs past go away now.

**Comment by Feynt** [comment]
Can confirm, no more tabs haunting my window.
