### ISSUE TITLE
All consoles clear when parent container is resized, but all text returns upon echo or scroll.

### ISSUE THREAD

**Issue by breakone9r** [demonnic/EMCO#9]
As the title says. If the parent container gets resized, the minis all just go blank..

![emco-whoopsie](https://user-images.githubusercontent.com/31798877/91104383-4a26d180-e633-11ea-8159-583e8d8ed054.png)
![emco-working](https://user-images.githubusercontent.com/31798877/91104386-4abf6800-e633-11ea-980e-277b40e0aa27.png)

Reproducing it seems pretty easy. Just resize the parent container.....

**Comment by demonnic** [comment]
this I think may be a Mudlet bug, EMCO is just using standard miniconsoles here.

**Comment by breakone9r** [comment]
Maybe, but I've never noticed it when I was using a regular minicons in that exact spot. I'll double check tomorrow...

Or if you want to check it yourself, the last 0.8.x version of my mmpkg was using a regular console, while the 0.9.x series uses emco.

**Comment by demonnic** [comment]
I mean maybe, but EMCO isn't doing anything to clear the miniconsole, so it's a Mudlet bug, the only question is what about the MC in EMCO is different from just a normal one. I'll see if I can take a look at it later.

**Comment by breakone9r** [comment]
Yeah, seems it may have been, as it seems to have resolved itself by updating too the latest mudlet dev build. So I'm not sure what's going on there. Feel free to close it if you want.
